version: 2
jobs:
  build:
    working_directory: ~/circleci
    environment:
      stage: ci
      project_config_dir: ~/circleci/circleci/src/settings
      DARKSKY_API_KEY: fake-api-key
      darksky_exclude: "minutely,hourly,flags"
    docker:
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: requirements_5-{{ .Branch }}-{{ checksum "requirements-test.txt" }}
      - run:
          name: Install Python dependencies in a virtual env
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-test.txt
      - save_cache:
          key: requirements_5-{{ .Branch }}-{{ checksum "requirements-test.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m pytest -vv --cov=met_service tests/
            coverage html -d artifacts
      - store_artifacts:
          path: artifacts
          destination: cov
